
// Import the functions you need from the SDKs you need
// This uses the modern ES Module syntax for browsers
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
  measurementId: "YOUR_MEASUREMENT_ID"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Export the app instance if you need to use it in other files
export { app };

// This part was auto-generated by Firebase so... don't edit it without a good reason thx :) 


// Function Firestore +1
async function incrementViewCounter(field) {
  const docRef = doc(db, "CiberShieldWebAnalitycs", "NumVistas");
  try {
    await updateDoc(docRef, {
      [field]: increment(1)
    });
    console.log(`Counter for ${field} incremented successfully!`);
  } catch (error) {
    console.error("Error incrementing view counter: ", error);
  }
}