name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto a tu rama de despliegue si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ajusta la versión de Node.js según tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build and Inject Secrets
        run: |
          # Vite detecta automáticamente las variables de entorno que empiezan con VITE_
          # cuando se ejecuta `npm run build`.
          # Aquí pasamos los secretos de GitHub Actions al entorno de compilación.
          VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} \
          VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }} \
          VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }} \
          VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }} \
          VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }} \
          VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }} \
          VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }} \
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Asegúrate de que esta es la carpeta de salida de tu build de Vite
          # Si tu repositorio se llama 'username.github.io' o 'orgname.github.io',
          # no necesitas especificar 'destination_dir'.
          # Si no, y quieres que se despliegue en un subdirectorio,
          # puedes usar 'destination_dir: base-path-for-your-app'
